spring.application.name=syncapp

spring.datasource.url=jdbc:postgresql://localhost:5432/sync_db
spring.datasource.username=postgres
spring.datasource.password=masuk123

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

resilience4j.circuitbreaker.instances.vendorApi.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.vendorApi.slidingWindowSize=5
resilience4j.circuitbreaker.instances.vendorApi.minimumNumberOfCalls=3
resilience4j.circuitbreaker.instances.vendorApi.failureRateThreshold=50
resilience4j.circuitbreaker.instances.vendorApi.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.vendorApi.permittedNumberOfCallsInHalfOpenState=2

spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.batch_versioned_data=true

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

app.jwt.secret=mySecretKeymySecretKeymySecretKey123456
app.jwt.expiration=86400000